# Generated by Django 3.1.5 on 2021-01-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('kipos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
                name = 'kiposuser',
                managers = [
                ],
        ),
        migrations.AddField(
                model_name = 'kiposuser',
                name = 'is_active',
                field = models.BooleanField(default = True),
        ),
        migrations.AddField(
                model_name = 'kiposuser',
                name = 'is_admin',
                field = models.BooleanField(default = False),
        ),
    ]
