# Generated by Django 3.1.5 on 2021-01-23 18:21

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kipos', '0002_auto_20210123_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='name',
            field=models.CharField(default='module', max_length=40),
        ),
        migrations.AddField(
            model_name='module',
            name='settings',
            field=jsonfield.fields.JSONField(default="{a:'a'}"),
        ),
    ]
